### ISSUE TITLE
Parse hex constants

### ISSUE THREAD

**Issue by aleofreddi** [aleofreddi/timel#26]
**Describe the bug**
TimEL is not able to parse hexadecimal constants, like `0x1`.

**Actual behavior**
```
java.lang.NumberFormatException: For input string: "0x1"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at net.vleo.timel.impl.parser.ParserTreeAdapter.visitTerminal(ParserTreeAdapter.java:255)
	at net.vleo.timel.impl.parser.ParserTreeAdapter.visitTerminal(ParserTreeAdapter.java:47)
```

**Expected behavior**
`0x1` (as well `0X1`) is interpreted correctly.

**Runtime**
Any

**Additional context**
/

**Comment by aleofreddi** [comment]
Fixed
