### ISSUE TITLE
Calling a function with non matching signature results in NPE

### ISSUE THREAD

**Issue by aleofreddi** [aleofreddi/timel#35]
**Describe the bug**
Compile `version(1)` or any other invalid function call that doesn't match a valid signature

**Actual behavior**
```
Aug 28 20:54:57 timel-demo java[23887]: java.lang.NullPointerException: null
Aug 28 20:54:57 timel-demo java[23887]: at net.vleo.timel.function.FunctionRegistry.lookup(FunctionRegistry.java:145) ~[timel-core-0.9.3-SNAPSHOT.jar!/:na]
Aug 28 20:54:57 timel-demo java[23887]: at net.vleo.timel.impl.intermediate.SyntaxTreeAdapter.visit(SyntaxTreeAdapter.java:97) ~[timel-core-0.9.3-SNAPSHOT.jar!/:na]
Aug 28 20:54:57 timel-demo java[23887]: at net.vleo.timel.impl.intermediate.SyntaxTreeAdapter.visit(SyntaxTreeAdapter.java:49) ~[timel-core-0.9.3-SNAPSHOT.jar!/:na]
Aug 28 20:54:57 timel-demo java[23887]: at net.vleo.timel.impl.parser.tree.FunctionCall.accept(FunctionCall.java:48) ~[timel-core-0.9.3-SNAPSHOT.jar!/:na]
Aug 28 20:54:57 timel-demo java[23887]: at net.vleo.timel.impl.intermediate.SyntaxTreeAdapter.lambda$visit$1(SyntaxTreeAdapter.java:119) ~[timel-core-0.9.3-SNAPSHOT.jar!/:na]
Aug 28 20:54:57 timel-demo java[23887]: at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_151]
Aug 28 20:54:57 timel-demo java[23887]: at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235) ~[na:1.8.0_151]
```

**Expected behavior**
`ParseException` should be thrown instead, including the suggested signatures.

**Runtime**
 - OS: Any
 - JVM version: Any
- TimEL version: `0.9.3-SNAPSHOT (14e3ae9574c5d66e73f6e51554349219b7761c34)`

**Additional context**
/

**Comment by aleofreddi** [comment]
Calling a non existing function triggers the same issue as well
